### PR TITLE
Add Docker Compose support

### PR DESCRIPTION
**Pull request by joshuaja**
Sorry this took so long to contribute back. Busy year :)

This builds a local Docker image called kk7ds/pynx584 and runs the container.

There are environment variables for:
- SERIAL
- BAUD
- CONNECT

### CODE REVIEW

**Comment by joshuaja** [comment]
@kk7ds  - FYI - I just realized the entrypoint.sh I have may not be the most up-to-date. If you could give me this evening to verify I'll let you know if it needs updating or if it's good to go.

**Comment by joshuaja** [comment]
@kk7ds - I believe everything should be good to review now. Thanks!

**Comment by joshuaja** [comment]
@kk7ds - were you able to take a look at this?

**Comment by kk7ds** [comment]
Sorry I dunno why I didn't see the notification for this

**Comment by zipperten** [comment]
This is fantastic. Thanks, now I canmove from hassberrian !

**Pull request merged**
