### PR TITLE
Adding Config For Binary Mode Support

### PR DESCRIPTION
**Pull request by drsweb**
@kk7ds  Sorry me again.  I forgot to update the readme to include the new config for binary mode.  If you want to add it, here's my edits for that.  After this, I'll leave you alone I promise.  :)

Thanks

### CODE REVIEW

**Comment by kk7ds** [comment]
Don't be silly ;)

Githib won't let me merge it with this PR anymore because it's closed (I think). I need to tag a release, so I'll cherry-pick that commit and add it underneath.

Thanks!

**Comment by drsweb** [comment]
You are awesome!  Thanks again!

**Comment by kk7ds** [comment]
I think we got everything from this merged, right? So I can close this?

**Comment by drsweb** [comment]
Yes, this can be closed.  Thanks!

**Pull request closed without merging**
